name: geirunner

on:
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        job_id: [FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque, FreeTanque]

    env:
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=kpljgl3_e6E"
      MENSAJE: "Raideados por Stefano365P"
      LLAMAR_ADMIN: "Raideados por Stefano365P"
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
