name: geirunner

on:
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 27
      matrix:
        job_id: [estrellita_en_el_lobby, soy_estrellita, estrellita_legend, estrellita_online, team_estrellita, estrellita_top1, estrellita_x, estrellita_main, xX_EstrellitaPro_Xx, estrellitaHD, la_estrellita_gamer, estrellita_real, estrellita_con_flow, estrellita_on_fire, el_retorno_de_estrellita, estrellita_4ever, mr_estrellita, estrellita_juega, queen_estrellita, estrellita_del_sur, estrellita_suprema, modo_estrellita, el_mago_estrellita, capitán_estrellita, estrellita_2025, estrellita_wins, elplan_de_estrellita, estrellita_random, estrellita_in_the_zone, estrellita_gg, topG_estrellita, big_estrellita, little_estrellita, estrellita_vr, no_soy_estrellita, el_estrellita, estrellita_lovers, estrellita_skins, estrellita_sin_team, estrellita_clutch, estrellita_movement, estrellita_focus, estrellita_soloQ, estrellita_mystery, estrellita_dorado, estrellita_rush, estrellita_galáctica, full_estrellita, not_estrellita, estrellita_legendaria, elcódigo_estrellita, estrellita_alpha, estrellita_hype, estrellita_zone, estrellita_skrrt, star_estrellita, pro_estrellita, estrellita_ops, only_estrellita, estrellita_run, estrellita_gameplay, estrellita_digital, estrellita_channel, estrellita_rebirth, estrellita_dance, highping_estrellita, estrellita_móvil, estrellita_fusion, estrellita_was_here, ultra_estrellita, estrellita_setup, estrellita_back, estrellita360, estrellita_creator, estrellita_positivo, new_estrellita, estrellita_plus, estrellita_update, club_estrellita, estrellita_cosmica, elshow_de_estrellita, coach_estrellita, soyyo_estrellita, estrellita_afk, estrellita_ayuda, estrellita_stream, la_cuenta_estrellita, estrellita_arcade, estrellita_vibes, estrellita_lobby_master, estrellita_nights, power_estrellita, turbo_estrellita, estrellita_open, estrellita_key, estrellita_jump, estrellita_time, estrellita_player, zona_estrellita]

    env:
      HAXBALL_ROOM_URL: "https://www.haxball.com/play?c=AWyYRclO8A0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias limpias (incluye puppeteer completo)
        run: |
          npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth
          npm ci

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar bot
        run: node botsstefano.js
        env:
          JOB_ID: ${{ matrix.job_id }}
        timeout-minutes: 60
