name: Run Node.js Script with Multiple Jobs

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      max_parallel:
        description: 'Maximum parallel jobs'
        required: false
        default: '11'
        type: string

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 11
      matrix:
        job_id: [
"thr1.AAAAAGjjOI8i_n9Sjmkryg.lyxphdKXXY0",
"thr1.AAAAAGjjOJ1I5Y86oqwPVg.IaiXIDK8nOw",
"thr1.AAAAAGjjOKWpeD3S72SJUQ.4mYQ7EmpGpM",
"thr1.AAAAAGjjOKyrb3N8S2aOfw.LwLVpLsv-nA",
"thr1.AAAAAGjjOLTaz75JjoAiYA.3w17MLSJoVk",
"thr1.AAAAAGjjOLpg-YpQhnnLog.PMQYhwx-SNI",
"thr1.AAAAAGjjOMAcu4S9SMIYdA.LXUzQ9XDUQU",
"thr1.AAAAAGjjOMfByyP3rI3Bog.Ft2zBuY-U88",
"thr1.AAAAAGjjONCELMX46-Swvg.FmsfaHhRr4E",
"thr1.AAAAAGjjONtFy2wnXePgQw.1cTGjeSaU0M",
"thr1.AAAAAGjjOO_3eTRrtbiDRg.fG9PG6UDd9s",
"thr1.AAAAAGjjOP_FRKIOrB5Ejw.WNGmFFAwlNY",
"thr1.AAAAAGjjOQrYyjKT17RJmg.QB6T9kDelzI",
"thr1.AAAAAGjjORG-yvt1rrA8Jg.-4NxSHTToaI",
"thr1.AAAAAGjjOR-wI4zY3ROvAQ.pKOMtzpa4_o",
"thr1.AAAAAGjjOTPy03eZE-g0jA.saeb1wCjQgc",
"thr1.AAAAAGjjOUAlugCBDVuZQw.j2wgwvNz19U",
"thr1.AAAAAGjjOUaAviZqzEOZdg.xcUDeCI_6Ow",
"thr1.AAAAAGjjOVYs0xjD1xi85g.2W6kdNP8km0",
"thr1.AAAAAGjjOWORIsJiyWl23w.wfE5gvU2zKY",
"thr1.AAAAAGjjOW5Ky8_bHC44lA.dYfWTMiEli0"
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Limpiar entorno previo
        run: rm -rf node_modules package-lock.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias (incluye haxball.js)
        run: |
          npm install haxball.js
          npm install  # Esto instalará también tus otras dependencias del package.json si existen

      - name: Esperar inicio sincronizado
        run: sleep $((RANDOM % 10 + 5))

      - name: Ejecutar script
        run: node hostbots.js
        env:
          JOB_ID: ${{ matrix.job_id }}
